apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-kontur-app
  labels:
    app: {{ .Release.Name }}-kontur-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-kontur-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-kontur-app
    spec:
      containers:
      - name: {{ .Release.Name }}-kontur-app
        image: {{ .Values.konturApp.image.repository }}:{{ .Values.javaApp.image.tag }}
        imagePullPolicy: {{ .Values.konturApp.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.konturApp.service.port }}
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
