apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx
  labels:
    app: {{ .Release.Name }}-nginx
spec:
  selector:
    app: {{ .Release.Name }}-nginx
  ports:
  - name: http
    port: {{ .Values.nginx.service.port }}
    targetPort: {{ .Values.nginx.service.port }}
  type: {{ .Values.nginx.service.type }}
